### ISSUE TITLE
No collection_dir in Jekyll config causes TypeError

### ISSUE THREAD

**Issue by mitchellbusby** [jekyll/jekyll-compose#96] opened 2019-06-09 01:15 UTC
I don't have a `collections_dir` key in my Jekyll config; I think #74 is throwing a TypeError:

```
Error:  no implicit conversion of nil into String
```

I think the arg parser needs to gracefully handle the lack of a key, but I don't know enough Ruby to do this myself 😅

Full traceback from running `$ bundle exec jekyll post "Hi" --trace`

```
Configuration file: /Users/mitchellbusby/repos/mitchell-busby/_config.yml
/Users/mitchellbusby/.rvm/gems/ruby-2.3.1/gems/jekyll-compose-0.9.0/lib/jekyll-compose/arg_parser.rb:36:in `join': no implicit conversion of nil into String (TypeError)
        from /Users/mitchellbusby/.rvm/gems/ruby-2.3.1/gems/jekyll-compose-0.9.0/lib/jekyll-compose/arg_parser.rb:36:in `source'
        from /Users/mitchellbusby/.rvm/gems/ruby-2.3.1/gems/jekyll-compose-0.9.0/lib/jekyll/commands/post.rb:35:in `process'
        from /Users/mitchellbusby/.rvm/gems/ruby-2.3.1/gems/jekyll-compose-0.9.0/lib/jekyll/commands/post.rb:13:in `block (2 levels) in init_with_program'
        from /Users/mitchellbusby/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /Users/mitchellbusby/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /Users/mitchellbusby/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /Users/mitchellbusby/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /Users/mitchellbusby/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /Users/mitchellbusby/.rvm/gems/ruby-2.3.1/gems/jekyll-3.3.0/exe/jekyll:13:in `<top (required)>'
        from /Users/mitchellbusby/.rvm/gems/ruby-2.3.1/bin/jekyll:23:in `load'
        from /Users/mitchellbusby/.rvm/gems/ruby-2.3.1/bin/jekyll:23:in `<main>'
        from /Users/mitchellbusby/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/mitchellbusby/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ashmaroli** [comment] 2019-06-09 05:48
@mitchellbusby Thank you for reporting this.
It looks like the issue is because of improper versioning: *We did not lock the Jekyll version at the time of release of `jekyll-compose-0.9.0`*

The solution for you is to update both `jekyll` and the `jekyll-compose` gems.
You're using `jekyll-3.3.0` and `jekyll-compose-0.9.0`. The latest versions are `3.8.5` and `0.10.1` respectively.

I'm closing this for now. I'll reopen if issue crops with with recent versions of the gems.

**Closed by ashmaroli** 2019-06-09 05:48 UTC
